import * as THREE from 'three';
import type { TilePrototype } from '../core/types/tile';
import type { TileRegions } from './svgRegions';
import { BASE_COLOR, TILE_SIZE, DETAIL } from './palette';
import { makeRng, svgToWorld, standard, centroid, pointInPolygon, type World2 } from './generators/util';
import { generateCity, cityBanner, generateGates } from './generators/city';
import { generateField } from './generators/field';
import { generateRoad } from './generators/road';
import { generateMonastery } from './generators/monastery';
import { tagSegmentMeshes } from './regionHighlight';

/**
 * Iteration 3/4 — procedural content per segment kind. The TS topology (`proto`)
 * provides semantics and a deterministic seed; the SVG-derived `regions`
 * provide boundaries. Each kind is generated by its own module under
 * `generators/`. City walls follow only the true outer boundary (tile-edge
 * connections and internal seams are excluded), and fields don't scatter
 * greenery underneath cities.
 */

/** The ground plate the tile sits on (slightly inset below y=0). */
function basePlate(): THREE.Mesh {
  const geometry = new THREE.BoxGeometry(TILE_SIZE, 0.04, TILE_SIZE);
  geometry.translate(0, -0.02, 0);
  const mesh = new THREE.Mesh(geometry, standard(BASE_COLOR));
  mesh.receiveShadow = true;
  return mesh;
}

// Eight compass directions, tried in order, for nudging the shield off-centre.
const SHIELD_OFFSET_DIRS: World2[] = [
  [1, 0], [0, 1], [-1, 0], [0, -1],
  [0.7071, 0.7071], [-0.7071, 0.7071], [0.7071, -0.7071], [-0.7071, -0.7071],
];

/**
 * Where a shielded city's heraldic banner stands: the city centroid nudged
 * off-centre so it doesn't collide with the player's claim gonfalon, which sits
 * at that same centroid (see `cityAnchor` in claimMarkers). Prefers the largest
 * offset that still lands inside a city part; falls back to the centroid for
 * cities too small to clear.
 */
function shieldBannerPos(parts: World2[][]): World2 {
  const c = centroid(parts.flat());
  for (const dist of [0.16, 0.12, 0.08]) {
    for (const [dx, dz] of SHIELD_OFFSET_DIRS) {
      const p: World2 = [c[0] + dx * dist, c[1] + dz * dist];
      if (parts.some((poly) => pointInPolygon(p, poly))) return p;
    }
  }
  return c;
}

/** Adds one shield banner per shielded city (parts of a city share a localId). */
function addShieldBanners(group: THREE.Group, proto: TilePrototype, regions: TileRegions): void {
  const done = new Set<number>();
  for (const region of regions.polygons) {
    if (region.kind !== 'CITY') continue;
    const shielded = proto.segments.find((s) => s.localId === region.localId)?.isShielded === true;
    if (!shielded || done.has(region.localId)) continue;
    done.add(region.localId);
    const parts = regions.polygons
      .filter((r) => r.kind === 'CITY' && r.localId === region.localId)
      .map((r) => r.points.map(svgToWorld));
    group.add(cityBanner(shieldBannerPos(parts), DETAIL.cityBaseHeight));
  }
}

export function generateTile(proto: TilePrototype, regions: TileRegions, seed: string = proto.id): THREE.Group {
  const group = new THREE.Group();
  group.name = `tile-${proto.id}`;
  group.add(basePlate());

  const cityPolys: World2[][] = regions.polygons
    .filter((r) => r.kind === 'CITY')
    .map((r) => r.points.map(svgToWorld));

  // CITY / FIELD areas → procedural settlements / countryside.
  for (const region of regions.polygons) {
    const rng = makeRng(`${seed}:${region.kind}:${region.localId}`);
    const poly = region.points.map(svgToWorld);
    const objects = region.kind === 'CITY'
      ? generateCity(poly, rng, cityPolys)
      : generateField(poly, rng, cityPolys);
    group.add(...objects);
  }

  addShieldBanners(group, proto, regions);

  // ROAD → ribbon + curb along the centreline. Ownership is shown by a wayside
  // lantern in the claim-marker layer (see claimMarkers.ts), so the road mesh
  // carries no claim tag and is never recoloured.
  const roadCenterlines: World2[][] = regions.roads.map((road) => road.centerline.map(svgToWorld));
  for (let i = 0; i < regions.roads.length; i++) {
    group.add(...generateRoad(roadCenterlines[i], regions.roads[i].width / 100));
  }

  // GATEHOUSE → where a road meets a city wall, straddling the boundary.
  group.add(...generateGates(cityPolys, roadCenterlines, DETAIL.cityBaseHeight));

  // MONASTERY → cloister building at the marker point.
  for (const marker of regions.markers) {
    const segment = new THREE.Group();
    for (const piece of generateMonastery(svgToWorld(marker.pos))) {
      segment.add(piece);
    }
    tagSegmentMeshes(segment, marker.localId, 'MONASTERY');
    group.add(segment);
  }

  return group;
}
