import * as THREE from 'three';
import type { TilePrototype } from '../core/types/tile';
import type { TileRegions } from './svgRegions';
import { BASE_COLOR, TILE_SIZE } from './palette';
import { makeRng, svgToWorld, standard } from './generators/util';
import { generateCity } from './generators/city';
import { generateField } from './generators/field';
import { generateRoad } from './generators/road';
import { generateMonastery } from './generators/monastery';

/**
 * Iteration 3 — procedural content per segment kind. The TS topology (`proto`)
 * provides semantics and a deterministic seed; the SVG-derived `regions`
 * provide boundaries. Each kind is generated by its own module under
 * `generators/` (city walls + houses, field trees, road ribbon, monastery
 * building), so the look of each kind can evolve independently.
 */

/** The ground plate the tile sits on (slightly inset below y=0). */
function basePlate(): THREE.Mesh {
  const geometry = new THREE.BoxGeometry(TILE_SIZE, 0.04, TILE_SIZE);
  geometry.translate(0, -0.02, 0);
  const mesh = new THREE.Mesh(geometry, standard(BASE_COLOR));
  mesh.receiveShadow = true;
  return mesh;
}

export function generateTile(proto: TilePrototype, regions: TileRegions): THREE.Group {
  const group = new THREE.Group();
  group.name = `tile-${proto.id}`;
  group.add(basePlate());

  // CITY / FIELD areas → procedural settlements / countryside.
  for (const region of regions.polygons) {
    const rng = makeRng(`${proto.id}:${region.kind}:${region.localId}`);
    const poly = region.points.map(svgToWorld);
    const objects = region.kind === 'CITY' ? generateCity(poly, rng) : generateField(poly, rng);
    group.add(...objects);
  }

  // ROAD → ribbon + curb along the centreline.
  for (const road of regions.roads) {
    group.add(...generateRoad(road.centerline.map(svgToWorld), road.width / 100));
  }

  // MONASTERY → cloister building at the marker point.
  for (const marker of regions.markers) {
    group.add(...generateMonastery(svgToWorld(marker.pos)));
  }

  return group;
}
